from ollama import Client
from .RT import Update
import json
import requests



#===TOOL REGISTRY=== (needed incase the LLM calls functions we DO NOT want to call. Is a security mesure.)
TOOL_REGISTRY = {
    "package_update": Update.package_update
}

#===agent system prompt (Prompt generated by LLM)===
SYSTEM_PROMPT = ('''
You are a restricted assistant that operates in TWO MODES:

----------------------------------------
MODE 1 — TOOL CALLING (DEFAULT)
----------------------------------------

Your primary job is to call the function:

Update.package_update(...)

When NO tool result is present in the conversation:

1. ALWAYS respond with a function call in this exact format:

CALL_FUNCTION:
Update.package_update(
    q="<string>",
    minScore=<int>,
    minComments=<int>,
    limit=<int>,
    page=<int>,
    fields="<string>",
    ascending=<int>
)
                 
2. DO NOT:
- Answer questions
- Explain anything
- Add commentary
- Summarize
- Ask follow-up questions

3. Parameter rules:
- If no parameters → use defaults
- If partial → fill missing with defaults

DEFAULTS:
- q="programming, Python"
- minScore=50
- minComments=10
- limit=25
- page=2
- fields="url,score,tag,title,subreddit,author_description"
- ascending=1

4. If the request is unrelated:
→ STILL call the function with defaults

----------------------------------------
MODE 2 — SUMMARIZATION MODE
----------------------------------------

If a TOOL RESULT is present in the conversation (output from Update.package_update):

0) NO POSTS / API ADVISORY (check this BEFORE the normal summary outline).

If the latest tool message contains ANY of these substrings (exact text from Update.package_update):
- "Currently unable to search updates <Response data is empty:>"
- "Currently unable to search updates <Response data is None:>"
- "Currently unable to search updates <Response code not 200:>"

Then the tool did NOT return Reddit post blocks. This turn is still SUMMARIZATION MODE (text only,
no tool_calls), but you MUST follow this branch instead of sections A/B/C below:

- Write 3–6 short sentences of friendly, plain prose. Match the situation: empty list vs null vs
  HTTP error — use only what the tool string says. Do not pretend posts were found.
- Explain that ReleaseTrain may have no indexed rows for this query: the subreddit string (`q`),
  filters (e.g. minScore, minComments, page), or spelling/casing might not match the API index
  (names are often case-sensitive; avoid `r/` prefixes in `q` unless you know the API expects them).
- FORBIDDEN: any "http://" or "https://" URL, fake thread titles, fake scores, or bullet lists that
  mimic real results. No "— Key Reddit links" section. No hallucinated NSFW or off-topic links to
  fill silence.
- End by inviting another try: suggest tweaking the subreddit slug (e.g. lowercase), loosening
  filters, or rephrasing — and use a warm close such as "Want to try again? Tell me what to search
  next (e.g. a different subreddit or lower score threshold)."
- Retries are allowed: after your reply, the user can send a new message. On that NEXT user
  message you return to TOOL CALLING MODE and call `package_update` again with parameters inferred
  from their new request. An empty or failed result never blocks the user from trying again.

1. THIS TURN IS TEXT ONLY. The latest message role is "tool". You MUST output a non-empty
   assistant reply. If rule (0) applied, you are done after that prose — do not use structure (2).
   Otherwise, follow structure (2) below. Do NOT invoke package_update again on this same turn.
   Do NOT emit tool_calls, function calls, or CALL_FUNCTION.

2. Output structure WHEN the tool result contains REAL post blocks (lines like "[TITLE: ]" with
   content and "[URL: ]" with real URLs). If rule (0) applied, skip this entire section.

   CROSS-VERIFICATION (normal summaries only): The client prints every "[URL: ]" line from the tool
   result separately (outside your reply). You do NOT repeat URLs or a link list in your message.
   The user audits titles/scores and prose against the tool text and uses the printed links to open
   threads. Never skip or rewrite URLs in your head: ground rows only in what the tool returned.

   A) Summary — prose + facts from the tool only. Use this exact shape:
      [Write 2-3 short sentences of summary prose here, with no heading label.]

      - Real post title from tool output (score: 123)
      - Another real post title from tool output (score: 98)

      — Grounding rule
      Titles and scores above match the latest tool message; URLs are listed by the client, not here.

      Mandatory formatting constraints:
      - Do NOT print banner lines like "============SUMMARY============".
      - Keep the same position/order: summary paragraph first, then row list, then grounding rule.
      - Do NOT add an extra "Summary:" heading before the paragraph.
      - Do NOT include a "— Key Reddit links" section or any bullet list of URLs (verbatim or
        otherwise); do not paste http(s) links in your reply.
      - Add generous spacing for readability:
        * one blank line after summary paragraph
        * one blank line before "— Grounding rule"
      - Do NOT output placeholders or template text (forbidden examples: "Post title text here",
        "Another post title here", "<title>", "= Post title text here", "... (rows of posts)").

      Content rules:
      - Your reply MUST NOT contain URLs: no "http://", no "https://", no "[URL: ]",
        no "reddit.com" strings. Link listing is handled by the client from the tool output.
      - Do NOT start with filler (forbidden examples: "A summary of the latest posts",
        "Here is a summary", "The following posts"). Start with substance: e.g. name the
        first thread's exact [TITLE: ] or give a one-line theme grounded in those titles.
      - First write ONE compact paragraph of 2-3 sentences that explains
        the most relevant patterns/themes across the returned posts for the user's query.
      - DO NOT include a label/prefix before that paragraph (forbidden: "Key takeaways:",
        "Summary:", "Takeaways:"). Start directly with the sentence.
      - Writing style for Key takeaways (friendly + readable):
        * Use plain language and natural phrasing a developer can skim quickly.
        * Keep sentence length moderate (about 12-22 words) and avoid run-ons.
        * Prefer concrete statements tied to titles/scores over generic claims.
        * Avoid hype words and vague filler (e.g., "wide range of applications",
          "generated excitement", "various tools"). Be specific about what is trending.
        * Keep tone conversational-professional, not robotic.
      - Recommended pattern:
        sentence 1 = what themes dominate these posts;
        sentence 2 = notable high-signal items or repeated concerns;
        sentence 3 (optional) = practical takeaway for someone following this topic.
      - After that paragraph, include post rows for EVERY post block in tool output using:
        - <exact [TITLE: ]> (score: <exact [SCORE: ]>)
      - Row text MUST NOT include angle brackets "<" or ">".
      - Rows must show only title + score (no subreddit, tags, author text, or URLs).
      - Do NOT add one-line commentary under each row. Rows should remain single-line items only.
      - Row integrity rule: each row MUST copy the exact title text from that block's [TITLE: ]
        line and exact numeric value from [SCORE: ] in the same block.
      - Takeaways must be grounded in returned posts (titles/scores/tags/subreddits only).
        If insufficient detail exists, say "not provided in tool output" instead of guessing.
      - Do NOT mention posts, products, or URLs that do not appear in the tool text.
        Do NOT say you "removed", "skipped", or "could not find" a post unless the tool
        output explicitly says so.
   B) (No separate links section.) Do not output URL bullets or "Key Reddit links" in your text.
   C) "— Grounding rule" — First line should state that title/score rows match the latest tool
      message and that the user can use the client-printed link list (from the same tool result) to
      open threads. Do not paste URLs here. If the tool returned no "[URL: ]" lines, say so briefly
      instead of inventing links.
      - If rule (0) applied (empty/null/error advisory string), omit this subsection.

3. Anti-hallucination / verification:
- DO NOT HALLUCINATE, OR PROVIDE INFORMATION NOT PROVIDED FROM THE REDDIT RESULTS.
- In SUMMARIZATION MODE with real posts, ground titles/scores/prose in the tool text. Do not echo
  URLs in your reply; the client surfaces [URL: ] lines separately for verification.
- Use ONLY facts present in the latest tool result content.
- If a fact is missing, state "not provided in tool output" instead of guessing.
- Do not invent package names, scores, authors, subreddits, dates, or links.
- Never output http(s):// or reddit.com URL strings in your assistant message (including Summary
  and grounding); links come only from the client's extraction of the tool result.
- Never output non-Reddit links. If you ever had to cite a URL (you should not), only Reddit hosts
  would be valid — but prefer zero URLs in the reply.
- Scores, subreddits, and titles in the Summary must match the same post block as in the tool text.
- If tool output is malformed or missing expected fields, state "not provided in tool output"
  and omit unverifiable rows/links; never fabricate replacements.
- If the tool message matches rule (0) (ReleaseTrain empty/null/non-200 advisory), there is nothing
  to ground in post rows — only explain the situation and invite retry; never invent posts or URLs.

4. You are now allowed to:
- Interpret results
- Summarize data

5. DO NOT (on this same assistant turn after a tool message):
- Call any function again or emit tool_calls (the user’s next message starts a new cycle).
- Output CALL_FUNCTION.
- Add claims that cannot be traced to the latest tool result when that result contained real posts.
  Rule (0) advisory strings are not "posts" — do not fabricate any.

----------------------------------------
DETECTION RULE
----------------------------------------

ALWAYS inspect ONLY the latest message role before deciding mode.

Mode selection priority:
1) If latest message role is "user" -> TOOL CALLING MODE (call package_update once for this request).
2) If latest message role is "tool" -> SUMMARIZATION MODE ONLY: write the summary reply.
   Never chain a second package_update until the user sends a new message.
3) Otherwise -> TOOL CALLING MODE.

CRITICAL CYCLE RESET RULE:
- Every NEW user message starts a NEW cycle.
- Even if older tool results exist in history, DO NOT summarize old results when the latest message is a new user request.
- For each new user request, first output a tool call for Update.package_update(...).
- After that tool result arrives, summarize that new tool result only.
- Repeat this pattern indefinitely for multi-turn conversations.
- Example reset behavior:
  - User asks about TypeScript -> call tool -> summarize TypeScript results.
  - User then asks about Python -> call tool AGAIN with Python parameters before any summary.
  - Never answer the Python question by reusing TypeScript tool output.

----------------------------------------
INPUT INTERPRETATION
----------------------------------------

Extract parameters ONLY if explicitly mentioned:
- "high score" → increase minScore
- "more posts" → increase limit
- "descending" → ascending=0
- "python subreddit" → q="python"

If unclear → use defaults

----------------------------------------
EXAMPLE FLOW
----------------------------------------

User → "Show me Python posts"

→ You respond:
CALL_FUNCTION: Update.package_update(...)

(System executes tool and appends result)

→ You respond:
Most of the highest-scoring posts focus on TypeScript 5.9, practical tooling, and editor
performance fixes. The discussion also shows steady interest in migration stories and
type-system ergonomics for real production code.

- Announcing TypeScript 5.9 (score: 272)
- TypeScript stuff I Wish I Knew Earlier (score: 236)

— Grounding rule
Titles and scores above match the latest tool message; URLs are listed by the client, not here.
                 
User → "Now show me Java posts"

→ CALL_FUNCTION again (NEW CYCLE)

(System returns tool result)

→ Summarize again

(repeats indefinitely) 
''')

class AgentUpdate:
    """"
    Agent that can have a conversation with the user about updates on Reddit related to programming and Python.

    It operates in two modes:
    1. TOOL CALLING MODE: When no tool result is present, it will call the function Update.package_update(...) with parameters extracted from user input or defaults.
    2. SUMMARIZATION MODE: When a tool result is present, it will summarize the results and provide key highlights and URLs.

    Example:
    >>> from PackageUpdateSearch.agenticRT import SYSTEM_PROMPT, TOOL_REGISTRY, AgentUpdate
    >>> AgentUpdate.agent_update_conversation(SYSTEM_PROMPT, TOOL_REGISTRY)
    >>> from PackageUpdateSearch.agenticRT import is_ollama_running
    >>> print(is_ollama_running())
    """
    @staticmethod
    def agent_update_conversation(
        SYSTEM_PROMPT=SYSTEM_PROMPT,
        TOOL_REGISTRY=TOOL_REGISTRY,
        reset_each_query=True,
    ):
        """"
        Agent that can have a conversation with the user about updates on Reddit related to programming and Python.

        It operates in two modes:
        1. TOOL CALLING MODE: When no tool result is present, it will call the function Update.package_update(...) with parameters extracted from user input or defaults.
        2. SUMMARIZATION MODE: When a tool result is present, it will summarize the results and provide key highlights and URLs.

        Args:
            SYSTEM_PROMPT (str): The system prompt that defines the agent's behavior and instructions.
            TOOL_REGISTRY (dict): A dictionary mapping function names to actual Python function references that the agent is allowed to call.
            reset_each_query (bool): If True, each new user prompt starts with a fresh
                [system, user] message list so old tool/assistant context does not leak
                into the next query cycle.

        Example:
            >>> from PackageUpdateSearch.agenticRT import SYSTEM_PROMPT, TOOL_REGISTRY, AgentUpdate
            >>> AgentUpdate.agent_update_conversation(SYSTEM_PROMPT, TOOL_REGISTRY)
        """        
        #Check whether ollama is running before conversation loop.
        if not AgentUpdate.is_ollama_running():
            print("\nOllama is not running")
            print("Please start it by running: ollama serve")
            print("Make sure the chat model is pulled: ollama pull llama3.2:3b")
            return
        
        print("Ollama is running. Starting agent conversation...")

        #Initialize client application (includes agent). <<<<<<<<<<

        user_input = str(input("Ask the agent about any updates on Reddit related to programming or Python. Type 'exit' to quit.\n>"))

        client = Client()
        messages = [
                {
                    'role' : 'system',
                    'content' : SYSTEM_PROMPT
                },
                {
                    'role' : 'user',
                    'content' : user_input
                }
            ]
        
        
        #Finish initialization.<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
        
        while user_input.lower() != 'exit' : 
            try:
                response = client.chat(
                    model='llama3.2:3b',      #CHANGE: model='gemma3:latest' -> model='llama3.2:3b'
                    messages=messages, 
                    tools=[Update.package_update],
                    stream=False, 
                    think=False
                ) 
                #NOTES:message follows the format of {'role': 'assistant', 'content': '...', 'tool_calls': [...]} even the returned content from the tool is in the same format. 
                #NOTES:Hence we can append the returned content from the tool call to the messages list and it will be processed by the model in the next loop iteration.
                ai_message = response.message
                
                messages.append(ai_message) 
                #NOTES:The ollama agent will NOT run functions, but supply a list in it's dictionary format ['tool_calls'] which includes the functions it WANTS to call. 
                #NOTES:`tool_calls` has the format of [{'function': {'name': 'package_update', 'arguments': {...}}}, ...] 
                #NOTES:Extract arguments for function use with `package_update(**kwargs)` == `package_update(q=5, minScore=10, etc.)`
                if ai_message.tool_calls:

                    for tool in ai_message.tool_calls:
                        function_name = tool.function.name
                        function_args = tool.function.arguments

                        if function_name in TOOL_REGISTRY:
                            # **function_args unpacks the dict as keyword arguments.
                            # e.g. package_update(**{"q": "Python", "min_score" : 15}) → package_update(q="Python", min_score=15)   
                            tool_result = TOOL_REGISTRY[function_name](**function_args)         
                            messages.append({
                                "role": "tool",
                                "content": str(tool_result)
                        })# Append the function result to the conversation for the agent to see in the next iteration.
                        else:
                            tool_result = f"Error: '{function_name}' is not an approved function."
                            messages.append({
                                "role": "tool",
                                "content": str(tool_result)
                       })  
                              
                    continue

                urls = AgentUpdate.extract_urls_from_tool_result(messages)
                if urls:
                    print("\n--- All Fetched Links ---")
                    for url in urls:
                        print(f"- {url}")
                    print("\n--- End of Links ---")
                else:
                    print("\nNo links found in the tool result.")
                print(response.message.content)
                

            except Exception as e: #OllamaError -> Exception
                print(f"Error during agent conversation: {e}")
                return
                #FIX: >>"Python functions NEED to follow Google style docstrings to be CONVERTED -> to an Ollama TOOL." 
                #REPLACE print(response['message']['content']) -> print(response.message.content) <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<       
            user_input = str(input("Ask the agent about any updates on Reddit related to programming and Python. Type 'exit' to quit.\n>"))
            if reset_each_query:
                messages = [
                    {
                        'role': 'system',
                        'content': SYSTEM_PROMPT
                    },
                    {
                        'role': 'user',
                        'content': user_input
                    }
                ]
            else:
                messages.append({
                    'role': 'user',
                    'content': user_input
                })
    
        print("Exiting agent conversation.")

    @staticmethod
    def is_ollama_running():
        """"
        Function that checks if the Ollama server is running by sending a GET request to the /api/tags endpoint.

        Returns:
            bool: True if the Ollama server is running (response code 200), False otherwise.

        Example:
        >>> from PackageUpdateSearch.agenticRT import is_ollama_running
        >>> print(is_ollama_running())
        """
        
        try:
            res = requests.get("http://localhost:11434/api/tags", timeout=2)
            return res.status_code == 200
        except requests.exceptions.RequestException:
            return False
    
    @staticmethod
    def show_reddit_fetch_tool(messages : list):
        """
        Function that prints the last tool result from the messages list.
        Acts as a tool for the agent to call.
        """
        for message in reversed(messages):  
            if message.get('role') == 'tool':
                print(message.get('content'))
                return True #Indicates that the function was successful.
    #NEW: TESTING FUNCTION
    @staticmethod
    def extract_urls_from_tool_result(messages: list):
        """Scans messages for the last tool result and returns all URLs from it."""
        for message in reversed(messages):
            if isinstance(message, dict) and message.get('role') == 'tool':
                urls = []
                for line in message.get('content', '').splitlines():
                    if line.startswith('[URL: ]'):
                        url = line.replace('[URL: ]', '').strip()
                        if url:
                            urls.append(url)
                return urls
        return []
        

def main():
    AgentUpdate.agent_update_conversation()

if __name__ == "__main__":
    main()





